version: "3"
services:
    backend:
        build: ./backend
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: "your-database-connection-string"
            SESSION_SECRET: "your-session-secret"
        volumes:
            - ./backend/images:/usr/src/app/images

    frontend:
        build: ./frontend
        ports:
            - "4200:4200"
        environment:
            API_URL: "http://localhost:3000"
