BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Attendees] ALTER COLUMN [first_name] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Attendees] ALTER COLUMN [last_name] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Attendees] ALTER COLUMN [bio] NVARCHAR(1000) NULL;

-- AlterTable
ALTER TABLE [dbo].[Organizers] ALTER COLUMN [company] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Organizers] ALTER COLUMN [bio] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
